version: "2.4"

networks:
  service-net:
    external: true

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.4
    container_name: etcd
    restart: always
    networks:
      - service-net
    environment:
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/var/lib/etcd
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: nginx:1.19.1-alpine
        CONTAINER_PACKAGE_URL: mirrors.ustc.edu.cn
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/www/:rw
      - ./nginx/ssl:/ssl:rw
      - ./nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf:ro
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./nginx/log:/var/log/nginx/:rw
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - service-net


  mysql:
    image: mysql:8.0.13
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql/:rw
    restart: always
    networks:
      - service-net
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"